#!/usr/bin/env node
/**
 * Interactive setup wizard — run: npm run setup
 * Creates .env.local and validates your Supabase connection.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";

const root = resolve(process.cwd());
const envLocalPath = resolve(root, ".env.local");
const envExamplePath = resolve(root, ".env.example");

const rl = createInterface({ input, output });

async function ask(question, defaultValue = "") {
  const suffix = defaultValue ? ` [${defaultValue}]` : "";
  const answer = await rl.question(`${question}${suffix}: `);
  return answer.trim() || defaultValue;
}

function maskKey(key) {
  if (key.length <= 12) return "••••••••";
  return `${key.slice(0, 8)}…${key.slice(-4)}`;
}

async function main() {
  console.log("\n╔══════════════════════════════════════════╗");
  console.log("║   DailyChapter — Setup Wizard            ║");
  console.log("╚══════════════════════════════════════════╝\n");

  if (existsSync(envLocalPath)) {
    const overwrite = await ask(
      ".env.local already exists. Overwrite? (y/N)",
      "n",
    );
    if (overwrite.toLowerCase() !== "y") {
      console.log("\nKeeping existing .env.local. Run: npm run env:check\n");
      rl.close();
      return;
    }
  }

  console.log("Get your values from:");
  console.log("  Supabase Dashboard → Project Settings → API\n");

  const supabaseUrl = await ask("NEXT_PUBLIC_SUPABASE_URL");
  const supabaseKey = await ask("NEXT_PUBLIC_SUPABASE_ANON_KEY");
  const appUrl = await ask("NEXT_PUBLIC_APP_URL", "http://localhost:3000");

  if (!supabaseUrl || !supabaseKey) {
    console.error("\n❌ URL and anon key are required. Setup cancelled.\n");
    rl.close();
    process.exit(1);
  }

  let exampleExtras = "";
  if (existsSync(envExamplePath)) {
    const example = readFileSync(envExamplePath, "utf8");
    const optionalBlock = example
      .split("# =============================================================================")
      .slice(3)
      .join("# =============================================================================");
    if (optionalBlock) {
      exampleExtras = "\n" + optionalBlock.trim();
    }
  }

  const envContent = `# Auto-generated by: npm run setup
# ${new Date().toISOString()}

NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseKey}
NEXT_PUBLIC_APP_URL=${appUrl}
${exampleExtras ? "\n" + exampleExtras : ""}
`;

  writeFileSync(envLocalPath, envContent, "utf8");

  console.log("\n✓ Created .env.local");
  console.log(`  URL:  ${supabaseUrl}`);
  console.log(`  Key:  ${maskKey(supabaseKey)}`);
  console.log(`  App:  ${appUrl}\n`);

  // Validate by loading into process.env and running check logic
  process.env.NEXT_PUBLIC_SUPABASE_URL = supabaseUrl;
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY = supabaseKey;
  process.env.NEXT_PUBLIC_APP_URL = appUrl;

  console.log("Running env:check…\n");
  rl.close();

  const { spawnSync } = await import("node:child_process");
  const result = spawnSync("node", ["scripts/check-env.mjs"], {
    stdio: "inherit",
    cwd: root,
  });

  const projectRef = supabaseUrl.match(/https:\/\/([^.]+)\.supabase\.co/)?.[1];

  console.log("\n─── Still need to do in Supabase Dashboard ───\n");
  console.log("Authentication → URL Configuration:");
  console.log(`  Site URL:       ${appUrl}`);
  console.log(`  Redirect URLs:  ${appUrl}/auth/callback`);
  if (appUrl.includes("localhost")) {
    console.log("                  https://YOUR-APP.vercel.app/auth/callback  (add when deployed)");
  }
  console.log("\nAuthentication → Providers → enable Email, Google, GitHub\n");

  if (projectRef) {
    console.log("─── Apply database schema (run in terminal) ───\n");
    console.log("  npx supabase login");
    console.log(`  npx supabase link --project-ref ${projectRef}`);
    console.log("  npx supabase db push\n");
  }

  console.log("─── Vercel (after deploy) ───\n");
  console.log("  Add the same 3 env vars in Vercel → Settings → Environment Variables");
  console.log("  Then Redeploy.\n");

  console.log("─── Start the app ───\n");
  console.log("  npm run dev");
  console.log("  Open http://localhost:3000\n");

  process.exit(result.status ?? 0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
